#!/bin/bash
export BUILD_DIR=build/ios
echo "build output: $BUILD_DIR"
#rm -rf $BUILD_DIR/CMakeCache.txt
rm -rf $BUILD_DIR/*
cmake -E make_directory $BUILD_DIR
cmake -E chdir $BUILD_DIR cmake -G Xcode -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DCMAKE_TOOLCHAIN_FILE=$(dirname $0)/toolchain_ios64.cmake ../..
#-DCMAKE_BUILD_TYPE=Debug